# =============================================================================
# ETL Pipeline — Phase 0B: Parse Unstructured Clinical Notes → Structured CSVs
# Project : Early Disease Prediction Using Healthcare Data Warehouse
# Script  : etl_pipeline/parse_unstructured.py
#
# PURPOSE:
#   Read the unstructured clinical text notes generated by
#   generate_unstructured.py and extract structured tabular data using
#   NLP techniques (regex pattern matching, text normalisation, field
#   extraction).  This demonstrates the Silver Layer transformation
#   from raw unstructured text → clean structured DataFrames.
#
# INPUT:
#   datasets/unstructured/
#     ├── autism_clinical_notes.txt
#     ├── diabetes_clinical_notes.txt
#     └── stroke_clinical_notes.txt
#
# OUTPUT:
#   datasets/cleaned/
#     ├── autism_cleaned.csv     (same schema as before)
#     ├── diabetes_cleaned.csv
#     └── stroke_cleaned.csv
#
# HOW TO RUN:
#   python etl_pipeline/parse_unstructured.py
# =============================================================================

import os
import re
import sys
from typing import cast

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# 0.  Path Resolution
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(SCRIPT_DIR, "..")
UNSTRUCTURED_DIR = os.path.join(ROOT_DIR, "datasets", "unstructured")
CLEANED_DIR = os.path.join(ROOT_DIR, "datasets", "cleaned")

os.makedirs(CLEANED_DIR, exist_ok=True)

# Input unstructured text files
IN_AUTISM = os.path.join(UNSTRUCTURED_DIR, "autism_clinical_notes.txt")
IN_DIABETES = os.path.join(UNSTRUCTURED_DIR, "diabetes_clinical_notes.txt")
IN_STROKE = os.path.join(UNSTRUCTURED_DIR, "stroke_clinical_notes.txt")

# Output cleaned CSVs
OUT_AUTISM = os.path.join(CLEANED_DIR, "autism_cleaned.csv")
OUT_DIABETES = os.path.join(CLEANED_DIR, "diabetes_cleaned.csv")
OUT_STROKE = os.path.join(CLEANED_DIR, "stroke_cleaned.csv")


# ---------------------------------------------------------------------------
# 1.  Utility Helpers
# ---------------------------------------------------------------------------

def banner(title: str, width: int = 72, char: str = "=") -> None:
    print("\n" + char * width)
    print(f"  {title}")
    print(char * width)


def sub_step(message: str) -> None:
    print(f"    ▸  {message}")


def assert_no_missing(df: pd.DataFrame, dataset_name: str) -> None:
    """Hard assertion — raise if any NaN remains after extraction."""
    remaining = int(df.isnull().sum().sum())
    if remaining > 0:
        bad_cols = df.columns[df.isnull().any()].tolist()
        raise ValueError(
            f"[{dataset_name}] Extraction incomplete — "
            f"{remaining} NaN(s) remain in: {bad_cols}"
        )
    print("    ✔  Zero missing values confirmed.")


# ---------------------------------------------------------------------------
# 2.  Split raw text into individual records
# ---------------------------------------------------------------------------

def split_records(text: str) -> list[str]:
    """Split a text file into individual patient records using the
    '--- END OF RECORD #XXXXX ---' delimiter."""
    records = re.split(r"---\s*END OF RECORD\s*#\d+\s*---", text)
    # Filter out empty strings
    records = [r.strip() for r in records if r.strip()]
    return records


# ---------------------------------------------------------------------------
# 3.  PARSE AUTISM CLINICAL NOTES
# ---------------------------------------------------------------------------

def parse_autism_record(record: str) -> dict:
    """Extract structured fields from a single autism clinical note."""
    data: dict = {}

    # Extract Age
    age_match = re.search(r"(\d+)-year-old", record)
    if age_match:
        data["Age"] = int(age_match.group(1))

    # Extract Sex
    sex_match = re.search(r"\d+-year-old\s+(male|female)", record, re.IGNORECASE)
    if sex_match:
        data["Sex"] = 1 if sex_match.group(1).lower() == "male" else 0

    # Extract AQ-10 items (A1 through A10)
    for i in range(1, 11):
        col = f"A{i}"
        # Match pattern: "Item A1: ..." — endorsed (YES) or not endorsed (NO)
        pattern = rf"Item\s+{col}:.*?—\s*(endorsed|not endorsed)"
        item_match = re.search(pattern, record, re.IGNORECASE)
        if item_match:
            data[col] = 1 if item_match.group(1).lower() == "endorsed" else 0

    # Calculate AQ_Score
    aq_cols = [f"A{i}" for i in range(1, 11)]
    if all(c in data for c in aq_cols):
        data["AQ_Score"] = sum(data[c] for c in aq_cols)

    # Extract Jaundice
    if re.search(r"History of neonatal jaundice is noted", record, re.IGNORECASE):
        data["Jaundice"] = 1
    elif re.search(r"No history of neonatal jaundice", record, re.IGNORECASE):
        data["Jaundice"] = 0

    # Extract Family_ASD
    if re.search(
        r"Positive family history of Autism Spectrum Disorder", record, re.IGNORECASE
    ):
        data["Family_ASD"] = 1
    elif re.search(
        r"No family history of Autism Spectrum Disorder", record, re.IGNORECASE
    ):
        data["Family_ASD"] = 0

    # Extract Class (YES/NO → 1/0)
    class_match = re.search(r"Classification:\s*(YES|NO)", record, re.IGNORECASE)
    if class_match:
        data["Class"] = 1 if class_match.group(1).upper() == "YES" else 0

    return data


def parse_autism_notes(filepath: str) -> pd.DataFrame:
    """Parse the full autism clinical notes file into a DataFrame."""
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()

    records = split_records(text)
    parsed = [parse_autism_record(rec) for rec in records]
    df = pd.DataFrame(parsed)

    # Enforce column order to match original cleaned format
    expected_cols = [
        "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10",
        "Age", "Sex", "Jaundice", "Family_ASD", "Class", "AQ_Score",
    ]
    df = df[expected_cols]

    # Enforce dtypes
    int8_cols = [f"A{i}" for i in range(1, 11)] + [
        "Sex", "Jaundice", "Family_ASD", "Class", "AQ_Score",
    ]
    df[int8_cols] = df[int8_cols].astype(np.int8)
    df["Age"] = df["Age"].astype(np.int16)

    return df


# ---------------------------------------------------------------------------
# 4.  PARSE DIABETES CLINICAL NOTES
# ---------------------------------------------------------------------------

DIABETES_SYMPTOM_PATTERNS = {
    "Polyuria": r"excessive urination \(polyuria\)",
    "Polydipsia": r"excessive thirst \(polydipsia\)",
    "sudden weight loss": r"sudden unexplained weight loss",
    "weakness": r"generalized weakness and fatigue",
    "Polyphagia": r"excessive hunger \(polyphagia\)",
    "Genital thrush": r"recurrent genital thrush infections",
    "visual blurring": r"episodes of visual blurring",
    "Itching": r"persistent itching of the skin",
    "Irritability": r"notable irritability and mood changes",
    "delayed healing": r"delayed wound healing",
    "partial paresis": r"partial paresis of the extremities",
    "muscle stiffness": r"muscle stiffness and joint pain",
    "Alopecia": r"hair loss \(alopecia\)",
    "Obesity": r"clinical obesity",
}


def parse_diabetes_record(record: str) -> dict:
    """Extract structured fields from a single diabetes clinical note."""
    data: dict = {}

    # Extract Age
    age_match = re.search(r"(\d+)-year-old", record)
    if age_match:
        data["Age"] = int(age_match.group(1))

    # Extract Gender
    gender_match = re.search(r"\d+-year-old\s+(male|female)", record, re.IGNORECASE)
    if gender_match:
        data["Gender"] = 1 if gender_match.group(1).lower() == "male" else 0

    # Extract symptoms — look in the "reports" and "denies" sections
    reports_section = ""
    denies_section = ""

    # Find "reports the following symptoms:" section
    reports_match = re.search(
        r"reports the following symptoms:(.*?)(?=denies:|Total symptoms|CLINICAL ASSESSMENT)",
        record,
        re.DOTALL | re.IGNORECASE,
    )
    if reports_match:
        reports_section = reports_match.group(1)

    # Find "denies:" section
    denies_match = re.search(
        r"denies:(.*?)(?=Total symptoms|CLINICAL ASSESSMENT)",
        record,
        re.DOTALL | re.IGNORECASE,
    )
    if denies_match:
        denies_section = denies_match.group(1)

    # Also check "denies all screened symptoms"
    denies_all = bool(
        re.search(r"denies all screened symptoms", record, re.IGNORECASE)
    )

    for symptom_col, pattern in DIABETES_SYMPTOM_PATTERNS.items():
        if denies_all:
            data[symptom_col] = 0
        elif re.search(pattern, reports_section, re.IGNORECASE):
            data[symptom_col] = 1
        elif re.search(pattern, denies_section, re.IGNORECASE):
            data[symptom_col] = 0
        else:
            # Fallback: search the entire record
            if re.search(pattern, record, re.IGNORECASE):
                # Check if it's in the "reports" context
                # Find the symptom and check if it's after "reports" or "denies"
                symptom_pos = re.search(pattern, record, re.IGNORECASE)
                if symptom_pos:
                    preceding_text = record[: symptom_pos.start()]
                    last_reports = preceding_text.rfind("reports")
                    last_denies = preceding_text.rfind("denies")
                    if last_reports > last_denies:
                        data[symptom_col] = 1
                    else:
                        data[symptom_col] = 0
                else:
                    data[symptom_col] = 0
            else:
                data[symptom_col] = 0

    # Extract Class (Positive/Negative → 1/0)
    class_match = re.search(
        r"Risk Classification:\s*(Positive|Negative)", record, re.IGNORECASE
    )
    if class_match:
        data["Class"] = 1 if class_match.group(1).lower() == "positive" else 0

    return data


def parse_diabetes_notes(filepath: str) -> pd.DataFrame:
    """Parse the full diabetes clinical notes file into a DataFrame."""
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()

    records = split_records(text)
    parsed = [parse_diabetes_record(rec) for rec in records]
    df = pd.DataFrame(parsed)

    # Enforce column order
    expected_cols = [
        "Age", "Gender",
        "Polyuria", "Polydipsia", "sudden weight loss", "weakness",
        "Polyphagia", "Genital thrush", "visual blurring", "Itching",
        "Irritability", "delayed healing", "partial paresis",
        "muscle stiffness", "Alopecia", "Obesity",
        "Class",
    ]
    df = df[expected_cols]

    # Enforce dtypes
    binary_cols = ["Gender"] + list(DIABETES_SYMPTOM_PATTERNS.keys()) + ["Class"]
    df[binary_cols] = df[binary_cols].astype(np.int8)
    df["Age"] = df["Age"].astype(np.int16)

    return df


# ---------------------------------------------------------------------------
# 5.  PARSE STROKE CLINICAL NOTES
# ---------------------------------------------------------------------------

def parse_stroke_record(record: str) -> dict:
    """Extract structured fields from a single stroke clinical note."""
    data: dict = {}

    # Extract Gender (Male, Female, or Other)
    gender_match = re.search(
        r"^\s*(Male|Female|Other)\s+patient", record, re.MULTILINE | re.IGNORECASE
    )
    if gender_match:
        g = gender_match.group(1).lower()
        if g == "male":
            data["gender"] = 1
        elif g == "female":
            data["gender"] = 0
        else:
            data["gender"] = -1  # sentinel for "Other" — will be dropped

    # Extract Age (float for stroke — e.g., 0.08 for infants)
    age_match = re.search(r"([\d.]+)\s+years of age", record)
    if age_match:
        data["age"] = float(age_match.group(1))

    # Extract ever_married
    if re.search(r"currently or has been previously married", record, re.IGNORECASE):
        data["ever_married"] = 1
    elif re.search(r"has never been married", record, re.IGNORECASE):
        data["ever_married"] = 0

    # Extract work_type
    work_match = re.search(r"Employment status:\s*(.+?)\s*sector\.", record, re.IGNORECASE)
    if work_match:
        work_val = work_match.group(1).strip()
        data["work_type"] = work_val
    else:
        work_match2 = re.search(r"Employment status:\s*(.+?)\.", record, re.IGNORECASE)
        if work_match2:
            data["work_type"] = work_match2.group(1).strip()

    # Extract Residence_type
    if re.search(r"resides in an urban area", record, re.IGNORECASE):
        data["Residence_type"] = 1
    elif re.search(r"resides in an? rural area", record, re.IGNORECASE):
        data["Residence_type"] = 0

    # ── Extract comorbidities (hypertension / heart_disease) ────────────────
    # The comorbidities section has three patterns:
    #   1. "No significant comorbidities (no hypertension, no heart disease)"
    #   2. "Significant comorbidities include: documented hypertension"
    #      (only hypertension, no heart disease mentioned → heart_disease=0)
    #   3. "Significant comorbidities include: documented hypertension,
    #      history of heart disease"
    no_comorbid = bool(
        re.search(r"No significant comorbidities", record, re.IGNORECASE)
    )
    has_hypertension = bool(
        re.search(r"documented hypertension", record, re.IGNORECASE)
    )
    has_heart_disease = bool(
        re.search(r"history of heart disease", record, re.IGNORECASE)
    )

    if no_comorbid:
        data["hypertension"] = 0
        data["heart_disease"] = 0
    else:
        data["hypertension"] = 1 if has_hypertension else 0
        data["heart_disease"] = 1 if has_heart_disease else 0

    # Extract avg_glucose_level
    glucose_match = re.search(r"Average glucose level:\s*([\d.]+)\s*mg/dL", record)
    if glucose_match:
        data["avg_glucose_level"] = float(glucose_match.group(1))

    # Extract BMI
    bmi_match = re.search(r"BMI:\s*([\d.]+)\s*kg/m", record)
    if bmi_match:
        data["bmi"] = float(bmi_match.group(1))
    elif re.search(r"BMI:\s*Not recorded", record, re.IGNORECASE):
        data["bmi"] = np.nan  # Will be imputed later

    # Extract smoking_status
    smoking_match = re.search(r"Smoking history:\s*(.+?)\.", record, re.IGNORECASE)
    if smoking_match:
        data["smoking_status"] = smoking_match.group(1).strip()

    # Extract stroke outcome (Class)
    if re.search(r"Outcome:\s*Stroke\b", record, re.IGNORECASE):
        data["Class"] = 1
    elif re.search(r"Outcome:\s*No Stroke", record, re.IGNORECASE):
        data["Class"] = 0

    return data


def parse_stroke_notes(filepath: str) -> pd.DataFrame:
    """Parse the full stroke clinical notes file into a DataFrame."""
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()

    records = split_records(text)
    parsed = [parse_stroke_record(rec) for rec in records]
    df = pd.DataFrame(parsed)

    # ── Apply the same cleaning steps as the original clean.py ───────────────

    # Drop rows where gender == 'Other' (sentinel value -1)
    other_mask = df["gender"] == -1
    other_count = int(other_mask.sum())
    if other_count > 0:
        df = df[~other_mask].reset_index(drop=True)
        sub_step(
            f"Removed {other_count} row(s) where gender == 'Other' "
            f"(too sparse for encoding)"
        )

    # BMI Imputation — grouped-median by age bracket (same strategy as clean.py)
    AGE_BINS: list[float] = [0.0, 18.0, 40.0, 60.0, 80.0, float("inf")]
    AGE_LABELS: list[str] = ["0-18", "19-40", "41-60", "61-80", "81+"]

    missing_bmi = int(df["bmi"].isnull().sum())
    if missing_bmi > 0:
        sub_step(f"BMI Imputation: {missing_bmi} missing values detected")

        df["age_bracket"] = pd.cut(
            cast(pd.Series, df["age"]),
            bins=AGE_BINS,
            labels=AGE_LABELS,
            right=True,
        )

        # Per-bracket median imputation
        df["bmi"] = pd.Series(
            df.groupby("age_bracket", observed=True)["bmi"].transform(
                lambda grp: grp.fillna(grp.median())
            ),
            index=df.index,
        )

        # Fallback: global median
        remaining_bmi = int(df["bmi"].isnull().sum())
        if remaining_bmi > 0:
            global_median = float(df["bmi"].median())
            df["bmi"] = df["bmi"].fillna(global_median)

        df = df.drop(columns=["age_bracket"])
        sub_step(f"BMI imputed: {missing_bmi} → 0 missing")

    # Enforce column order
    expected_cols = [
        "gender", "age", "hypertension", "heart_disease", "ever_married",
        "work_type", "Residence_type", "avg_glucose_level", "bmi",
        "smoking_status", "Class",
    ]
    df = df[expected_cols]

    # Enforce dtypes
    int8_cols = [
        "gender", "hypertension", "heart_disease", "ever_married",
        "Residence_type", "Class",
    ]
    for col in int8_cols:
        df[col] = df[col].astype(np.int8)
    df["age"] = df["age"].astype(np.float32)
    df["avg_glucose_level"] = df["avg_glucose_level"].astype(np.float32)
    df["bmi"] = df["bmi"].astype(np.float32)

    return df


# ===========================================================================
# 6.  MAIN EXECUTION
# ===========================================================================

def main() -> None:
    banner("PHASE 0B — PARSING UNSTRUCTURED CLINICAL NOTES → STRUCTURED CSVs")

    # ── Pre-flight checks ────────────────────────────────────────────────────
    banner("STEP 1 — PRE-FLIGHT CHECKS", char="-")

    for filepath, name in [
        (IN_AUTISM, "Autism"),
        (IN_DIABETES, "Diabetes"),
        (IN_STROKE, "Stroke"),
    ]:
        if not os.path.isfile(filepath):
            print(f"\n  [ERROR] Missing unstructured file: {filepath}")
            print("  Run etl_pipeline/generate_unstructured.py first.")
            sys.exit(1)
        size_kb = os.path.getsize(filepath) / 1024
        sub_step(f"Found: {os.path.basename(filepath)} ({size_kb:.1f} KB)")

    # ── Parse Autism ─────────────────────────────────────────────────────────
    banner("STEP 2 — PARSING: AUTISM CLINICAL NOTES", char="-")

    sub_step("Applying NLP/Regex extraction on autism_clinical_notes.txt...")
    sub_step("  Technique: Pattern matching for AQ-10 items, demographics, diagnosis")
    df_autism = parse_autism_notes(IN_AUTISM)
    sub_step(f"  Extracted: {df_autism.shape[0]:,} records × {df_autism.shape[1]} columns")
    assert_no_missing(df_autism, "Autism")

    # ── Parse Diabetes ───────────────────────────────────────────────────────
    banner("STEP 3 — PARSING: DIABETES CLINICAL NOTES", char="-")

    sub_step("Applying NLP/Regex extraction on diabetes_clinical_notes.txt...")
    sub_step("  Technique: Symptom detection via medical terminology matching")
    df_diabetes = parse_diabetes_notes(IN_DIABETES)
    sub_step(f"  Extracted: {df_diabetes.shape[0]:,} records × {df_diabetes.shape[1]} columns")
    assert_no_missing(df_diabetes, "Diabetes")

    # ── Parse Stroke ─────────────────────────────────────────────────────────
    banner("STEP 4 — PARSING: STROKE CLINICAL NOTES", char="-")

    sub_step("Applying NLP/Regex extraction on stroke_clinical_notes.txt...")
    sub_step("  Technique: Clinical entity extraction + grouped-median BMI imputation")
    df_stroke = parse_stroke_notes(IN_STROKE)
    sub_step(f"  Extracted: {df_stroke.shape[0]:,} records × {df_stroke.shape[1]} columns")
    assert_no_missing(df_stroke, "Stroke")

    # ── Save cleaned CSVs ────────────────────────────────────────────────────
    banner("STEP 5 — SAVING STRUCTURED CSVs", char="-")

    save_map = {
        OUT_AUTISM: (df_autism, "autism_cleaned.csv"),
        OUT_DIABETES: (df_diabetes, "diabetes_cleaned.csv"),
        OUT_STROKE: (df_stroke, "stroke_cleaned.csv"),
    }

    for filepath, (df, filename) in save_map.items():
        df.to_csv(filepath, index=False)
        size_kb = os.path.getsize(filepath) / 1024
        print(
            f"  [SAVED]  {filename:<30}  "
            f"{df.shape[0]:>6,} rows × {df.shape[1]:>2} cols  "
            f"({size_kb:.1f} KB)  →  {filepath}"
        )

    # ── Final Summary ────────────────────────────────────────────────────────
    banner("EXTRACTION COMPLETE — FINAL SUMMARY", char="-")

    print(f"\n  {'Dataset':<22} {'Rows':>7} {'Cols':>5} {'Missing':>8} {'Target=1 (%)':>14}")
    print(f"  {'-' * 22} {'-' * 7} {'-' * 5} {'-' * 8} {'-' * 14}")
    for name, df in [
        ("Autism Screening", df_autism),
        ("Diabetes Risk", df_diabetes),
        ("Stroke Prediction", df_stroke),
    ]:
        pos_pct = (df["Class"] == 1).mean() * 100
        missing = int(df.isnull().sum().sum())
        print(
            f"  {name:<22} {df.shape[0]:>7,} {df.shape[1]:>5} "
            f"{missing:>8} {pos_pct:>13.2f}%"
        )

    total = len(df_autism) + len(df_diabetes) + len(df_stroke)
    print(f"\n  Total records extracted from unstructured text: {total:,}")
    print(f"  All records successfully parsed with zero data loss.")
    print()
    banner(
        "Next Step: etl_pipeline/warehouse.py → Load into Star Schema",
        char="-",
    )
    print()


if __name__ == "__main__":
    main()
